### PR TITLE
nav2_waypoint_follower: Fix opencv includes

### PR DESCRIPTION
**Pull request by traversaro**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | No tickets. |
| Primary OS tested on | Windows |
| Robotic platform tested on | Not tested in any robot, it is a compilation-related change. |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

The path used for opencv includes in `nav2_waypoint_follower` was different from the one documented by opencv itself for its header, see for example:
* https://github.com/opencv/opencv/blob/4.9.0/samples/gpu/video_reader.cpp#L12
* https://github.com/opencv/opencv/blob/4.9.0/doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.markdown?plain=1#L32

and from how other ROS 2 packages include opencv headers, see:
* https://github.com/ros-perception/vision_opencv/blob/4.1.0/cv_bridge/include/cv_bridge/rgb_colors.hpp#L39

In all cases the `opencv4` part of the include path is not included, and on some platforms (in my case, Windows with libopencv installed via conda-forge) including it results in compilation errors such as:
~~~
2024-04-30T19:39:27.9695139Z %SRC_DIR%\ros-humble-nav2-waypoint-follower\src\work\include\nav2_waypoint_follower/plugins/photo_at_waypoint.hpp(35,10): fatal error C1083: Cannot open include file: 'opencv4/opencv2/core.hpp': No such file or directory [%SRC_DIR%\build\photo_at_waypoint.vcxproj]
~~~

As removing the `opencv4` the compilation should work fine on all supported nav2 platforms, I guess it should be ok to uniform the opencv inclusion style with official OpenCV documentation and the rest of ROS 2.

## Description of documentation updates required from your changes

No documentation changes should be required.

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Admittedly we don't have many windows users, so I'm not surprised :-) Let CI turn over but LGTM

**Review by SteveMacenski — APPROVED** [review]

**Comment by traversaro** [comment]
> Admittedly we don't have many windows users, so I'm not surprised :-) Let CI turn over but LGTM

To be honest, I was even surprised of finding it as an option in the PR template table. :D

**Comment by SteveMacenski** [comment]
There are Nav2 Windows users/tickets, but not many

**Comment by traversaro** [comment]
Thanks for the fast feedback!

**Pull request merged**
